[language-server.ltex-ls.config]
ltex.language = "en-GB"
ltex.dictionary = { "en-GB" = ["builtin"] }
ltex.disabledRules = { "en-GB" = ["PROFANITY"] }

[language-server.rust-analyzer.config]
rustfmt.extraArgs = ["+nightly"]

[[language]]
name = "markdown"
auto-format = true
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"] }

[[language]]
name = "git-commit"
rulers = [50, 72]
auto-format = true
language-servers = [{ name = "ltex-ls" }]
formatter = { command = "fold", args = ["-w", "72", "-s"] }

[[language]]
name = "typescript"
auto-format = true

[[language]]
name = "toml"
auto-format = true
