[language-server.ltex-ls.config]
ltex.language     = "en-GB"
ltex.dictionary = { "en-GB" = ["builtin"] }
ltex.disabledRules = { "en-GB" = ["PROFANITY"] }

[language-server.rust-analyzer.config]
rustfmt = { extraArgs = ["+nightly"] }

[language-server.solidity-language-server]
command = "nomicfoundation-solidity-language-server"
args = [ "--stdio" ]

[[language]]
name = "markdown"
auto-format = true
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"] }

[[language]]
name = "git-commit"
rulers = [50, 72]
auto-format = true
language-servers = [{ name = "ltex-ls" }]

[[language]]
name = "typescript"
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "toml"
auto-format = true

[[language]]
name = "yaml"
auto-format = true

[[language]]
name = "solidity"
auto-format = true
formatter = { command = "forge", args = ["fmt", "--raw", "-"] }
language-servers = [ { name = "solidity-language-server" } ]

[[language]]
name = "rust"
auto-format = true
