
[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.normal]
family = "RobotoMono Nerd Font Mono"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[general]
import = ["/home/go/.config/alacritty/themes/catppuccin/catppuccin-mocha.toml"]
