configurations:
  - host: imap.gmail.com
    port: 993
    tls: true
    username: george@shapeshed.com
    passwordCMD: "/home/go/.config/mutt/oauth/mutt_oauth2.py /home/go/.config/mutt/oauth/george@shapeshed.com"
    xoAuth2: true                 # token comes from passwordCMD
    idleLogoutTimeout: 29         # Gmail kills IDLE ~30m; refresh at 29
    wait: 1                       # seconds to debounce before running command
    boxes:
      - mailbox: "[Gmail]/All Mail"   # or "INBOX" (use -list to confirm exact name)
    onNewMail: "/usr/bin/mbsync -c /home/go/.config/isync/mbsyncrc -Va -a && /usr/bin/notmuch new"
    # onNewMailPost: "afew -tn"    # optional, runs after onNewMail
